import React, { useState, useEffect, useRef } from 'react';
import { fmtAssets, fmtPct, fmtMembers, fmtPctChange } from '../utils/format';

const QUARTER_OPTIONS = [
  { value: 4, label: '4 Quarters (1 Year)' },
  { value: 8, label: '8 Quarters (2 Years)' },
  { value: 12, label: '12 Quarters (3 Years)' },
];

export default function ReportModal({ cuNumber, onClose }) {
  const [quarters, setQuarters] = useState(8);
  const [data, setData] = useState(null);
  const [narrative, setNarrative] = useState(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState(null);
  const reportRef = useRef(null);

  // Fetch CU data on mount
  useEffect(() => {
    setLoading(true);
    setError(null);
    fetch(`/api/ncua/institutions/${cuNumber}`)
      .then((r) => { if (!r.ok) throw new Error('Failed'); return r.json(); })
      .then((d) => { setData(d); setLoading(false); })
      .catch(() => { setError('Could not load institution data.'); setLoading(false); });
  }, [cuNumber]);

  const generateReport = () => {
    setGenerating(true);
    setNarrative(null);

    fetch('/api/ncua/report', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        cu_number: cuNumber,
        quarters: quarters,
      }),
    })
      .then((r) => r.json())
      .then((d) => { setNarrative(d.narrative); setGenerating(false); })
      .catch(() => { setNarrative('Error generating report narrative.'); setGenerating(false); });
  };

  const handlePrint = () => {
    const printContent = reportRef.current;
    if (!printContent) return;
    const win = window.open('', '_blank');
    win.document.write(`
      <html>
      <head>
        <title>Call Report - ${data?.institution?.name || 'Credit Union'}</title>
        <style>
          body { font-family: 'IBM Plex Sans', -apple-system, sans-serif; padding: 40px; color: #1a1a18; line-height: 1.6; }
          h1 { font-size: 22px; margin-bottom: 4px; }
          h2 { font-size: 16px; margin-top: 28px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
          .report-subtitle { color: #6b6a64; font-size: 13px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; margin: 12px 0; }
          th { text-align: left; background: #f7f7f5; padding: 6px 10px; border-bottom: 2px solid #ddd; font-size: 11px; text-transform: uppercase; }
          td { padding: 5px 10px; border-bottom: 1px solid #eee; }
          .mono { font-family: 'IBM Plex Mono', monospace; }
          .section { margin-bottom: 20px; }
          .narrative { white-space: pre-wrap; font-size: 13px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 10px; color: #9c9a92; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>${printContent.innerHTML}
        <div class="footer">Generated by CallRpt AI · NCUA 5300 Call Report Data · ${new Date().toLocaleDateString()} · Not financial advice</div>
      </body>
      </html>
    `);
    win.document.close();
    setTimeout(() => win.print(), 500);
  };

  const inst = data?.institution;
  const latest = data?.latest;
  const trend = data?.trend?.slice(0, quarters) || [];
  const pcts = data?.percentiles || {};

  return (
    <div className="report-overlay" onClick={onClose}>
      <div className="report-modal" onClick={(e) => e.stopPropagation()}>
        <div className="report-modal-header">
          <h2>Generate Call Report</h2>
          <button type="button" className="report-close" onClick={onClose}>✕</button>
        </div>

        {loading && <div className="report-loading">Loading institution data...</div>}
        {error && <div className="report-error">{error}</div>}

        {!loading && data && !narrative && (
          <div className="report-config">
            <div className="report-inst-name">{inst?.name}</div>
            <div className="report-inst-sub">
              CU# {cuNumber} · {inst?.state} · {inst?.charter_type}
            </div>

            <label className="report-label">
              Historical Period
              <select
                value={quarters}
                onChange={(e) => setQuarters(Number(e.target.value))}
                className="report-select"
              >
                {QUARTER_OPTIONS.map((opt) => (
                  <option key={opt.value} value={opt.value}>{opt.label}</option>
                ))}
              </select>
            </label>

            <div className="report-preview">
              <div className="report-preview-label">Report will include:</div>
              <ul>
                <li>Executive Summary with AI-generated narrative</li>
                <li>Balance Sheet trends ({quarters} quarters)</li>
                <li>Profitability analysis (ROA, NIM, Efficiency)</li>
                <li>Capital adequacy & CAMEL classification</li>
                <li>Asset quality & delinquency trends</li>
                <li>Membership & growth analysis</li>
                <li>Strategic outlook & recommendations</li>
              </ul>
            </div>

            <button
              type="button"
              className="report-generate-btn"
              onClick={generateReport}
              disabled={generating}
            >
              {generating ? 'Generating Report...' : 'Generate Report'}
            </button>
          </div>
        )}

        {generating && (
          <div className="report-generating">
            <div className="report-spinner" />
            <p>Generating executive report with Claude AI...</p>
            <p className="report-gen-sub">This typically takes 15-30 seconds</p>
          </div>
        )}

        {narrative && !generating && (
          <>
            <div className="report-actions-bar">
              <button type="button" className="report-print-btn" onClick={handlePrint}>
                Print / Save PDF
              </button>
              <button type="button" className="report-regen-btn" onClick={() => setNarrative(null)}>
                New Report
              </button>
            </div>

            <div className="report-content" ref={reportRef}>
              <h1>{inst?.name}</h1>
              <div className="report-subtitle">
                NCUA 5300 Call Report Analysis · CU# {cuNumber} · {inst?.state} ·{' '}
                {latest?.quarter_label} · Generated {new Date().toLocaleDateString()}
              </div>

              {/* Key Metrics Summary */}
              <h2>Key Metrics at a Glance</h2>
              <table>
                <thead>
                  <tr>
                    <th>Metric</th>
                    <th>Current</th>
                    <th>Prior Quarter</th>
                    <th>Change</th>
                    <th>Peer Percentile</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    { label: 'Total Assets', key: 'total_assets', fmt: fmtAssets, pctKey: null },
                    { label: 'Members', key: 'member_count', fmt: fmtMembers, pctKey: null },
                    { label: 'ROA', key: 'roa', fmt: fmtPct, pctKey: 'roa' },
                    { label: 'Net Worth Ratio', key: 'net_worth_ratio', fmt: fmtPct, pctKey: 'net_worth_ratio' },
                    { label: 'Delinquency Rate', key: 'delinquency_ratio', fmt: fmtPct, pctKey: 'delinquency_ratio' },
                    { label: 'Loan-to-Share', key: 'loan_to_share_ratio', fmt: fmtPct, pctKey: 'loan_to_share' },
                    { label: 'NIM', key: 'net_interest_margin', fmt: fmtPct, pctKey: null },
                    { label: 'Efficiency Ratio', key: 'efficiency_ratio', fmt: fmtPct, pctKey: null },
                  ].map(({ label, key, fmt, pctKey }) => {
                    const curr = latest?.[key];
                    const prev = trend[1]?.[key];
                    const delta = curr != null && prev != null ? curr - prev : null;
                    return (
                      <tr key={key}>
                        <td>{label}</td>
                        <td className="mono">{curr != null ? fmt(curr) : '—'}</td>
                        <td className="mono">{prev != null ? fmt(prev) : '—'}</td>
                        <td className="mono">
                          {delta != null ? (
                            key === 'total_assets' || key === 'member_count'
                              ? fmt(delta)
                              : fmtPctChange(delta)
                          ) : '—'}
                        </td>
                        <td className="mono">
                          {pctKey && pcts[pctKey] != null ? `${Math.round(pcts[pctKey])}th` : '—'}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>

              {/* Historical Trend Table */}
              <h2>Historical Trend ({quarters} Quarters)</h2>
              <table>
                <thead>
                  <tr>
                    <th>Quarter</th>
                    <th>Assets</th>
                    <th>Members</th>
                    <th>ROA</th>
                    <th>NWR</th>
                    <th>Delinq.</th>
                    <th>L/S Ratio</th>
                  </tr>
                </thead>
                <tbody>
                  {trend.map((q) => (
                    <tr key={q.quarter_label}>
                      <td>{q.quarter_label}</td>
                      <td className="mono">{fmtAssets(q.total_assets)}</td>
                      <td className="mono">{fmtMembers(q.member_count)}</td>
                      <td className="mono">{fmtPct(q.roa)}</td>
                      <td className="mono">{fmtPct(q.net_worth_ratio)}</td>
                      <td className="mono">{fmtPct(q.delinquency_ratio)}</td>
                      <td className="mono">{fmtPct(q.loan_to_share_ratio)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              {/* CAMEL Classification */}
              {latest?.camel_class && (
                <>
                  <h2>Capital Classification</h2>
                  <p>
                    <strong>Current Classification:</strong> {latest.camel_class}
                    {' · '}Net Worth Ratio: {fmtPct(latest.net_worth_ratio)}
                  </p>
                </>
              )}

              {/* AI Narrative */}
              <h2>Executive Analysis</h2>
              <div className="narrative">{narrative}</div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
